services:
  - type: web
    name: havenstayhotel
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      bash -c "flask db upgrade && gunicorn main:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: havenstayhotel-db
          property: connectionString
      - key: FLASK_APP
        value: main.py

databases:
  - name: havenstayhotel-db
    databaseName: havenstay
    user: havenstay