"""update table columns

Revision ID: adc198ba46c0
Revises: 
Create Date: 2024-09-17 01:40:48.086640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adc198ba46c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_reservations', schema=None) as batch_op:
        batch_op.drop_constraint('table_reservations_table_id_fkey', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('table_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', name='bookingstatus'), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('table_reservations_table_id_fkey', 'tables', ['table_id'], ['id'])

    # ### end Alembic commands ###
